jobs:
- job: Build_Binaries
  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
  - task: GoTool@0
    inputs:
      version: '1.15'
      GOPATH: '$(Agent.BuildDirectory)/go'
      GOBIN: '$(GOPATH)/bin'

  - bash: |
      export PATH="$GOBIN:$PATH"
      . build.sh
    env:
      ARTIFACTS: '$(Build.ArtifactStagingDirectory)'
    displayName: Build

  - bash: . run-docker-tests.sh
    env:
      ARTIFACTS: '$(Build.ArtifactStagingDirectory)'
    displayName: Run docker tests

  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: binaries
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/binaries'
    displayName: 'Publish Artifact'

- job: Build_Images_Linux
  dependsOn: Build_Binaries
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Build Artifacts'
    inputs:
      downloadPath: artifacts
      artifactName: binaries

  - bash: |
      ./build-images-linux.sh
    displayName: 'Build images'

  - bash: |
      ./push-images-linux.sh
    env:
      DOCKER_PASSWORD: '$(DOCKER_PASSWORD)'
    condition: succeeded()
    displayName: 'Push images'

- job: Build_Images_Windows
  dependsOn: Build_Binaries
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Build Artifacts'
    inputs:
      downloadPath: artifacts
      artifactName: binaries

  - bash: |
      ./build-images-windows.sh
    displayName: 'Build images'

  - bash: |
      ./push-images-windows.sh
    env:
      DOCKER_PASSWORD: '$(DOCKER_PASSWORD)'
    condition: succeeded()
    displayName: 'Push images'
